- defaults:
    link:
      create: true
      force: true

- clean: ['~']

- link:
    ~/.atom:
    ~/.bashrc: 
    ~/.config/ntfy:
    ~/.dotfiles: ''
    ~/.emacs.d:
    ~/.emacs:
    ~/.gconf:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.nano:
    ~/.oh-my-zsh:
    ~/.profile:
    ~/.tmux.conf:
    ~/.zsh:
    ~/.zshrc:

- shell:
  - git update-submodules # after linking ~/.gitconfig
